version: "1.0"
services:
  flink-jobmanager:
    build: flink:1.19.1-java17
    container_name: flink-jobmanager
    ports:
      - "8081:8081"
    volumes:
      - ./apps:/opt/flink-apps
      - ./data:/opt/flink-data
      - flink-checkpoints:/opt/flink-checkpoints
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        queryable-state.enable: true

  flink-taskmanager-a:
    build: flink:1.19.1-java17
    container_name: flink-taskmanager-a
    ports:
      - "9069:9069"
    volumes:
      - flink-checkpoints:/opt/flink-checkpoints
    depends_on:
      - flink-jobmanager
    command: taskmanager
    deploy:
      replicas: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        taskmanager.numberOfTaskSlots: 2
        queryable-state.enable: true

  flink-taskmanager-b:
    build: flink:1.19.1-java17
    container_name: flink-taskmanager-b
    ports:
      - "9169:9069"
    volumes:
      - flink-checkpoints:/opt/flink-checkpoints
    depends_on:
      - flink-jobmanager
    command: taskmanager
    deploy:
      replicas: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        taskmanager.numberOfTaskSlots: 3
        queryable-state.enable: true

  zoo-a:
    image: confluentinc/cp-zookeeper:7.3.2
    hostname: zoo-a
    container_name: zoo-a
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zoo-a:2888:3888

  kafka-a:
    image: confluentinc/cp-kafka:7.3.2
    hostname: kafka-a
    container_name: kafka-a
    ports:
      - "9092:9092"
      - "29092:29092"
      - "9999:9999"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-a:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092,DOCKER://host.containers.internal:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo-a:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_HOSTNAME: ${DOCKER_HOST_IP:-127.0.0.1}
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
    depends_on:
      - zoo-a

volumes:
  flink-checkpoints:
