FROM flink:1.17.0-java11
# enable queryable state, see https://nightlies.apache.org/flink/flink-docs-release-1.17/docs/dev/datastream/fault-tolerance/queryable_state/#activating-queryable-state
RUN cp opt/flink-queryable-state-runtime-*.jar lib/
