name: Create PR from `develop` to `main`

on:
  schedule:
    - cron: "0 0 * * MON"  # Runs every Monday at midnight
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  create-develop-pr:
    runs-on: ubuntu-latest
    name: Create PR from `develop` to `main`

    steps:
      # Checkout the repository (this can be useful for future steps)
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # Fetch the latest commit SHAs for develop and main branches
      - name: Fetch branch SHAs
        id: fetch-commits
        run: |
          echo "Fetching latest commit SHAs for develop and main branches..."

          develop_sha=$(gh api /repos/$GITHUB_REPOSITORY/commits/refs/heads/develop -q '.sha')
          main_sha=$(gh api /repos/$GITHUB_REPOSITORY/commits/refs/heads/main -q '.sha')

          echo "Latest develop commit SHA: $develop_sha"
          echo "Latest main commit SHA: $main_sha"

          # Set the output using the new method with GITHUB_OUTPUT
          echo "develop_sha=$develop_sha" >> $GITHUB_OUTPUT
          echo "main_sha=$main_sha" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Create a pull request if develop is ahead of main
      - name: Create Pull Request (if necessary)
        run: |
          develop_sha="${{ steps.fetch-commits.outputs.develop_sha }}"
          main_sha="${{ steps.fetch-commits.outputs.main_sha }}"

          echo "Comparing develop ($develop_sha) with main ($main_sha)..."

          # Only create PR if develop is ahead of main
          if [[ $develop_sha != $main_sha ]]; then
              echo "Develop is ahead of main. Checking for existing PR..."

              # Check if a PR already exists
              existing_pr=$(gh api /repos/$GITHUB_REPOSITORY/pulls \
                -f head=develop \
                -f base=main -q '.[] | select(.head.ref=="develop" and .base.ref=="main") | .url')

              if [[ -z $existing_pr ]]; then
                  echo "No existing PR found. Creating a new pull request..."
                  gh api /repos/$GITHUB_REPOSITORY/pulls \
                    -f title="Automated PR: Develop to Main" \
                    -f body="This is an automated PR created to merge changes from develop to main." \
                    -f base=main \
                    -f head=develop
                  echo "Pull request created successfully!"
              else
                  echo "A PR from develop to main already exists: $existing_pr"
              fi
          else
              echo "No changes to merge; develop and main are up-to-date."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Add step to notify the result of the workflow (optional)
      - name: Notify Completion (Optional)
        if: always()
        run: |
          echo "GitHub Action completed."