name: Upsert `develop` branch

on:
  push:
    branches: main
  workflow_dispatch: # This allows manual triggering from the GitHub UI

jobs:
  rebase:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history so we can perform rebase

      # Set up Git user
      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # Rebase develop branch onto main
      - name: Rebase develop onto main
        run: |
          git checkout develop
          git fetch origin
          git rebase origin/main

      # Push changes back to develop branch after the rebase
      - name: Push rebased changes
        run: |
          git push --force-with-lease origin develop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}